logging_severity: INFO

mqtt_broker:
  host: localhost
  port: 1883
  keepalive: 60

ros2mqtt:
  loop_rate: 2
  queue_size: 10
  topic2topic:
    /chatter:
      to: chatter
      ros_type: std_msgs.msg.String
    /map_with_laser:
      to: map_with_laser
      ros_type: sensor_msgs.msg.Image
      converter: image_serializer

mqtt2ros:
  loop_rate: 2
  queue_size: 10
  topic2topic:
    number:
      to: /number
      ros_type: std_msgs.msg.Int32
      
  topic2service:
    backend/start_mapping:
      to: /bt/start_mapping
      ros_type: std_srvs.srv.Trigger
      response: bt/start_mapping_response
    backend/stop_mapping:
      to: /bt/stop_mapping
      ros_type: std_srvs.srv.Trigger
      response: bt/stop_mapping_response  
    backend/save_map:
      to: /bt/save_map
      ros_type: robot_slam_msgs.srv.BTSaveMap
      response: bt/save_map_response  
